
[env]
PATH = "/usr/local/bin:/usr/bin:/bin"

[font]
normal.family = "JetBrainsMono Nerd Font"

[terminal.shell]
program = "zellij"
args = ["attach", "--create"]

[window]
startup_mode = "Maximized"
padding = { x = 5, y = 5 }
opacity = 0.9
blur = true

[general]
import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[terminal]
